<?php
/**
 * RoundCube Calendar
 *
 * Plugin to add a calendar to RoundCube.
 *
 * @version 0.2 BETA 2
 * @author Lazlo Westerhof
 * @url http://rc-calendar.lazlo.me
 * @licence GNU GPL
 * @copyright (c) 2010 Lazlo Westerhof - Netherlands
 *
 **/

$labels = array();

// config
$labels['default_view'] = 'Изглед';
$labels['time_format'] = 'Формат на часовете';
$labels['timeslots'] = 'Полета на час';
$labels['first_day'] = 'Първи ден от седмицата';

// calendar
$labels['calendar'] = 'Календар';
$labels['day'] = 'Ден';
$labels['week'] = 'Седмица';
$labels['month'] = 'Месец';
$labels['new_event'] = 'Добавяне на събитие';
$labels['edit_event'] = 'Промяна на събитие';
$labels['save'] = 'Запис';
$labels['remove'] = 'Изтриване';
$labels['cancel'] = 'Отказ';
$labels['title'] = 'Заглавие';
$labels['description'] = 'Описание';
$labels['all-day'] = 'цял ден';
$labels['export'] = 'Запази като ICS';
$labels['category'] = 'Категория';
?>