<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels['default_view'] = 'Προεπιλεγμένη προβολή';
$labels['time_format'] = 'Μορφή ώρας';
$labels['first_day'] = 'Πρώτη ημέρα της εβδομάδας';
$labels['workinghours'] = 'Ώρες εργασίας';
$labels['add_category'] = 'Προσθήκη κατηγορίας';
$labels['remove_category'] = 'Αφαίρεση κατηγορίας';
$labels['defaultcalendar'] = 'Δημιουργία νέων συμβάντων στο';
$labels['eventcoloring'] = 'Χρωματισμός συμβάντος';
$labels['coloringmode0'] = 'Σύμφωνα με το ημερολόγιο';
$labels['coloringmode1'] = 'Σύμφωνα με την κατηγορία';
$labels['aftertrash'] = 'Μετακίνηση στα απορρίματα';
$labels['afterdelete'] = 'Διαγραφή μηνύματος';
$labels['afterflagdeleted'] = 'Σημείωση ως διεγραμμένου';
$labels['aftermoveto'] = 'Μεταφορά σε...';
$labels['itipoptions'] = 'Προσκλήσεις συμβάντος';
$labels['calendar'] = 'Ημερολόγιο';
$labels['calendars'] = 'Ημερολόγια';
$labels['category'] = 'Κατηγορία';
$labels['categories'] = 'Κατηγορίες';
$labels['createcalendar'] = 'Δημιουργία νέου ημερολογίου';
$labels['name'] = 'Όνομα';
$labels['color'] = 'Χρώμα';
$labels['day'] = 'Ημέρα';
$labels['week'] = 'Εβδομάδα';
$labels['month'] = 'Μήνας';
$labels['new'] = 'Νέο';
$labels['new_event'] = 'Νέο συμβάν';
$labels['edit_event'] = 'Επεξεργασία συμβάντος';
$labels['edit'] = 'Επεξεργασία';
$labels['save'] = 'Αποθήκευση';
$labels['removelist'] = 'Αφαίρεση από την λίστα';
$labels['cancel'] = 'Ακύρωση';
$labels['select'] = 'Επιλογή';
$labels['print'] = 'Εκτύπωση';
$labels['printtitle'] = 'Εκτύπωση ημερολογίων';
$labels['title'] = 'Περίληψη';
$labels['description'] = 'Περιγραφή';
$labels['all-day'] = 'ολοήμερο';
$labels['export'] = 'Εξαγωγή';
$labels['exporttitle'] = 'Εξαγωγή σε iCalendar';
$labels['exportrange'] = 'Συμβάντα από';
$labels['location'] = 'Τοποθεσία';
$labels['url'] = 'URL';
$labels['date'] = 'Ημερομηνία';
$labels['start'] = 'Έναρξη';
$labels['starttime'] = 'Ώρα έναρξης';
$labels['end'] = 'Λήξη';
$labels['endtime'] = 'Ώρα λήξης';
$labels['repeat'] = 'Επανάληψη';
$labels['selectdate'] = 'Επιλογή ημερομηνίας';
$labels['busy'] = 'Απασχολημένος';
$labels['outofoffice'] = 'Εκτός γραφείου';
$labels['status'] = 'Κατάσταση';
$labels['sensitivity'] = 'Ιδιωτικότητα';
$labels['comment'] = 'Σχόλιο';
$labels['created'] = 'Δημιουργήθηκε';
$labels['changed'] = 'Τελευταία τροποποίηση';
$labels['eventhistory'] = 'Ιστορικό';
$labels['createfrommail'] = 'Αποθήκευση συμβάντος ως';
$labels['importevents'] = 'Εισαγωγή συμβάντων';
$labels['importrange'] = 'Συμβάντα από';
$labels['onemonthback'] = '1 μήνα πριν';
$labels['nmonthsback'] = '$nr μήνες πριν';
$labels['findcalendars'] = 'Εύρεση ημερολογίων...';
$labels['searchterms'] = 'Όροι αναζήτησης';
$labels['calsearchresults'] = 'Διαθέσιμα ημερολόγια';
$labels['until'] = 'μέχρι';
$labels['today'] = 'Σήμερα';
$labels['tomorrow'] = 'Αύριο';
$labels['thisweek'] = 'Αυτή την εβδομάδα';
$labels['nextweek'] = 'Την επόμενη εβδομάδα';
$labels['prevweek'] = 'Την προηγούμενη εβδομάδα';
$labels['thismonth'] = 'Αυτό τον μήνα';
$labels['nextmonth'] = 'Τον επόμενο μήνα';
$labels['weekofyear'] = 'Εβδομάδα';
$labels['role'] = 'Ρόλος';
$labels['availability'] = 'Διαθ.';
$labels['confirmstate'] = 'Κατάσταση';
$labels['addattendee'] = 'Προσθήκη συμμετεχόντων';
$labels['roleorganizer'] = 'Οργανωτής';
$labels['cutypegroup'] = 'Ομάδα';
$labels['availbusy'] = 'Απασχολημένος';
$labels['availoutofoffice'] = 'Εκτός γραφείου';
$labels['tabsummary'] = 'Περίληψη';
$labels['savingdata'] = 'Αποθήκευση δεδομένων...';
$labels['objectchangelog'] = 'Αλλαγή ιστορικού';
?>
