<?php
/**
 * RoundCube Calendar
 *
 * Plugin to add a calendar to RoundCube.
 *
 * @version 0.2 BETA 3
 * @author Lazlo Westerhof
 * @author David Iribas
 * @url http://rc-calendar.lazlo.me
 * @licence GNU GPL
 * @copyright (c) 2010 Lazlo Westerhof - Netherlands
 *
 **/

$labels = array();

// config
$labels['default_view'] = 'Vista por defecto';
$labels['time_format'] = 'Formato hora';
$labels['timeslots'] = 'Periodos de hora';
$labels['first_day'] = 'Primer dia';

// calendar
$labels['calendar'] = 'Calendario';
$labels['day'] = 'Dia';
$labels['week'] = 'Semana';
$labels['month'] = 'Mes';
$labels['new_event'] = 'Nuevo evento';
$labels['edit_event'] = 'Editar evento';
$labels['save'] = 'Guardar';
$labels['remove'] = 'Borrar';
$labels['cancel'] = 'Cancelar';
$labels['title'] = 'Resumen';
$labels['description'] = 'Descripcion';
$labels['all-day'] = 'dia-completo';
$labels['export'] = 'Exportar a ICS';
$labels['category'] = 'Categoria';
?>
