<?php
/**
 * RoundCube Calendar
 *
 * Plugin to add a calendar to RoundCube.
 *
 * @version 0.2 BETA 2
 * @author Lazlo Westerhof
 * @url http://rc-calendar.lazlo.me
 * @licence GNU GPL
 * @copyright (c) 2010 Lazlo Westerhof - Netherlands
 *
 **/

$labels = array();

// config
$labels['default_view'] = 'Alap nézet';
$labels['time_format'] = 'Idõ formátum';
$labels['timeslots'] = 'Idõrés óránként';
$labels['first_day'] = 'A hét elsõ napja';

// calendar
$labels['calendar'] = 'Naptár';
$labels['day'] = 'Nap';
$labels['week'] = 'Hét';
$labels['month'] = 'Hónap';
$labels['new_event'] = 'Új bejegyzés';
$labels['edit_event'] = 'Bejegyzés szerkesztése';
$labels['save'] = 'Mentés';
$labels['remove'] = 'Törlés';
$labels['cancel'] = 'Mégse';
$labels['title'] = 'Tárgy';
$labels['description'] = 'Leírás';
$labels['all-day'] = 'Egész nap';
$labels['export'] = 'Exportálás ICS formátumba';
$labels['category'] = 'Kategória';
?>
