<?php
/**
 * RoundCube Calendar
 *
 * Plugin to add a calendar to RoundCube.
 *
 * @version 0.2 BETA 2
 * @author Lazlo Westerhof
 * @url http://rc-calendar.lazlo.me
 * @licence GNU GPL
 * @copyright (c) 2010 Lazlo Westerhof - Netherlands
 *
 **/

$labels = array();

// config
$labels['default_view'] = 'Visualização padrão';
$labels['time_format'] = 'Formato da hora';
$labels['timeslots'] = 'Caixas de tempo por hora';
$labels['first_day'] = 'Primeiro dia da semana';

// calendar
$labels['calendar'] = 'Calendário';
$labels['day'] = 'Dia';
$labels['week'] = 'Semana';
$labels['month'] = 'Mês';
$labels['new_event'] = 'Novo evento';
$labels['edit_event'] = 'Editar evento';
$labels['save'] = 'Gravar';
$labels['remove'] = 'Remover';
$labels['cancel'] = 'Cancelar';
$labels['title'] = 'Sumário';
$labels['description'] = 'Descrição';
$labels['all-day'] = 'dia-a-dia';
$labels['export'] = 'Exportar para ICS';
$labels['category'] = 'Categoria';
?>
